server:
  port: 9996

spring:
  application:
    name: sbms-mail-service
  config:
    import: optional:configserver:http://localhost:9999

  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: bad8db8d790dea
    password: f4e9e1910e1b56

management:
  observations:
    key-values:
      application: mail-service

rabbitmq:
  queue:
    email:
      name: email_queue
  exchange:
    email:
      name: email_exchange
  binding:
    email:
      name: email_routing_key