server:
  port: 8091

spring:
  application:
    name: sbms-comment-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/comment_service
    username: postgres
    password: postgres
    hikari:
      schema: public
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: comment-posted
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        schema:
          registry:
            url: http://127.0.0.1:8085
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

  config:
    import: optional:configserver:http://localhost:9999