server:
  port: 8080
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: OAuth2 Service
        url: /aggregate/SBMS-OAUTH2-SERVICE/v3/api-docs
      - name: Post Service
        url: /aggregate/SBMS-POST-SERVICE/v3/api-docs
      - name: Comment Service
        url: /aggregate/SBMS-COMMENT-SERVICE/v3/api-docs
  api-docs:
    path: /api-docs
spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:9999

management:
  observations:
    key-values:
      application: gateway-server