server:
  port: 8080
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:9999