server:
  port: 9999

spring:
  profiles:
    active: native
  application:
    name: sbms-config-service
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations