apiVersion: v1
kind: PersistentVolume
metadata:
  name: infra-pv
  labels:
    type: local
    app: infra
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data"