springdoc:
  swagger-ui:
    url: /swagger-ui.html
  api-docs:
    path: /api-docs

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

name:
  value: Config Service
spring:
  cloud:
    config:
      override-system-properties: false

management:
  tracing:
    sampling:
      probability: 1.0

# Use Eureka Server
service:
  auth:
    url: lb://SBMS-OAUTH2-SERVICE
  post_subreddit:
    url: lb://SBMS-POST-SERVICE


cors:
  allowedOrigins: http://localhost:4200, http://localhost:8080

rsa:
  private-key:
    classpath:certs/private.pem
  public-key:
    classpath:certs/public.pem