springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

name:
  value: Config Service
spring:
  cloud:
    config:
      override-system-properties: false
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      '[hibernate.format_sql]': false
      '[hibernate.generate_statistics]': false
      '[persistence.schema-generation.scripts.create-target]': create.sql

# Use Eureka Server
service:
  auth:
    url: lb://SBMS-OAUTH2-SERVICE
    http: http://localhost:8888
  post_subreddit:
    url: lb://SBMS-POST-SERVICE
  comment:
    url: lb://SBMS-COMMENT-SERVICE


cors:
  allowedOrigins: http://localhost:4200, http://localhost:8080

rsa:
  private-key:
    classpath:certs/private.pem
  public-key:
    classpath:certs/public.pem

logging:
  pattern:
    correlation: '[${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      show:
        details: always

loki:
  url: 'http://localhost:3100/loki/api/v1/push'